function clean_up(session_dir,filesToKeep,dirsToKeep)

% Removes unwanted files and directories
%
%   Usage:
%   clean_up(session_dir,filesToKeep,dirsToKeep)
%
%   Only the files and folders in 'filesToKeep' and 'foldersToKeep' will
%   remain.  All other files/folders will be deleted, with the exception of
%   bold directories in 'session_dir'.
%
%   Defaults:
%     filesToKeep = { ...
%         'README.md' ...
%         'LOG' ...
%         'LOGS' ...
%         'wdrf.tf.nii.gz' ...
%         'wdrf.tf.surf.rh.nii.gz' ...
%         'wdrf.tf.surf.lh.nii.gz' ...
%         's5.wdrf.tf.nii.gz' ...
%         's5.wdrf.tf.surf.rh.nii.gz' ...
%         's5.wdrf.tf.surf.lh.nii.gz' ...
%         };
%     dirsToKeep = { ...
%         'DICOMS' ...
%         'PulseOx' ...
%         'Protocols' ...
%         'MatFiles' ...
%         'Stimuli' ...
%         'wdrf.tf.feat' ...
%         's5.wdrf.tf.feat' ...
%         };
%
%   Written by Andrew S Bock Jan 2015
%   Updated on July 2016 by ASB, GF

%% set defaults
if ~exist('filesToKeep','var') || isempty(filesToKeep)
    filesToKeep = { ...
        'README.md' ...
        'LOG' ...
        'LOGS' ...
        'wdrf.tf.nii.gz' ...
        'wdrf.tf.surf.rh.nii.gz' ...
        'wdrf.tf.surf.lh.nii.gz' ...
        's5.wdrf.tf.nii.gz' ...
        's5.wdrf.tf.surf.rh.nii.gz' ...
        's5.wdrf.tf.surf.lh.nii.gz' ...
        'lh.ecc.nii.gz' ...
        'lh.pol.nii.gz' ...
        'lh.sig.nii.gz' ...
        'lh.co.nii.gz' ...
        'rh.ecc.nii.gz' ...
        'rh.pol.nii.gz' ...
        'rh.sig.nii.gz' ...
        'rh.co.nii.gz' ...
        'pulse_params.txt' ...
        'motion_params.txt' ...
        'anat_params.txt' ...
        'puls.mat' ...
        'puls.txt' ...
        'EchoSpacing' ...
        'EPI_TE' ...
        'slicetiming' ...
        };
end
if ~exist('dirsToKeep','var') || isempty(dirsToKeep)
    dirsToKeep = { ...
        'DICOMS' ...
        'PulseOx' ...
        'Protocols' ...
        'MatFiles' ...
        'Stimuli' ...
        'wdrf.tf.feat' ...
        's5.wdrf.tf.feat' ...
        'SpinEchoFieldMap' ...
        'preprocessing_scripts' ...
        'MPRAGE' ...
        'mc' ...
        };
end
sprintf('\n>>>> Cleaning up %s <<<<\n', session_dir)
disp('These files will be kept:');
disp(filesToKeep');
disp('These folders will be kept:');
disp(dirsToKeep');
%% find bold directories
b = find_bold(session_dir);

%% Remove all files and directories from session directory
% get all files
allFiles = listdir(session_dir,'files');
keepFiles = ismember(allFiles,filesToKeep);
for j = 1:length(allFiles)
    % delete those files not in 'filesToKeep'
    if ~keepFiles(j)
        disp(['Removing file ' fullfile(session_dir,allFiles{j})]);
        system(['rm -rf ' fullfile(session_dir,allFiles{j})]);
    end
end
% get all directories
allDirs = listdir(session_dir,'dirs');
keepDirs = ismember(allDirs,dirsToKeep);
for j = 1:length(allDirs)
    % ignore bold directories
    if ~ismember(allDirs{j},b)
        % delete those directories not in 'dirsToKeep'
        if ~keepDirs(j)
            disp(['Removing directory ' fullfile(session_dir,allDirs{j})]);
            system(['rm -rf ' fullfile(session_dir,allDirs{j})]);
        end
    end
end
%% remove all files and directories from bold directories
for i = 1:length(b)
    % get all files
    allFiles = listdir(fullfile(session_dir,b{i}),'files');
    keepFiles = ismember(allFiles,filesToKeep);
    for j = 1:length(allFiles)
        % delete those files not in 'filesToKeep'
        if ~keepFiles(j)
            disp(['Removing file ' fullfile(session_dir,b{i},allFiles{j})]);
            system(['rm -rf ' fullfile(session_dir,b{i},allFiles{j})]);
        end
    end
    % get all directories
    allDirs = listdir(fullfile(session_dir,b{i}),'dirs');
    keepDirs = ismember(allDirs,dirsToKeep);
    for j = 1:length(allDirs)
        % delete those directories not in 'dirsToKeep'
        if ~keepDirs(j)
            disp(['Removing directory ' fullfile(session_dir,b{i},allDirs{j})]);
            system(['rm -rf ' fullfile(session_dir,b{i},allDirs{j})]);
        end
    end
end
disp(['>>>> Cleanup completed ' session_dir ' <<<<']);