function create_all_script(params)

% Writes shell scripts to preprocess anatomical and functional MRI data
%
%   Usage:
%   create_all_script(params)
%
%   Written by Andrew S Bock Nov 2015

%% Set initial parameters
fname = fullfile(params.outDir,[params.jobName '_all.sh']);
fid = fopen(fname,'w');
fprintf(fid,'#!/bin/bash\n');
fprintf(fid,['SESS=' params.sessionDir '\n']);
fprintf(fid,['SUBJ=' params.subjectName '\n']);
fprintf(fid,['dicomDir=' params.dicomDir '\n']);
fprintf(fid,['useMRIcron=' num2str(params.useMRIcron) '\n']);
fprintf(fid,['isGE=' num2str(params.isGE) '\n\n']);
matlab_string = '"';
SUBJECTS_DIR = getenv('SUBJECTS_DIR');
%% Add anatomical scripts
if params.reconall % If a new subject, for which recon-all has not been run
    fprintf(fid,['matlab -nodisplay -nosplash -r ' ...
        '"sort_nifti(''$SESS'',''$dicomDir'',$useMRIcron,$isGE);"\n']);
    if params.isGE
        fprintf(fid,'recon-all -i $SESS/MPRAGE/001/MPRAGE.nii.gz -s $SUBJ -autorecon1\n');
        fprintf(fid,['mri_convert ' ...
            fullfile(SUBJECTS_DIR,params.subjectName,'mri','T1.mgz') ' ' ...
            fullfile(SUBJECTS_DIR,params.subjectName,'mri','T1.nii.gz') '\n']);
        fprintf(fid,['bet ' ...
            fullfile(SUBJECTS_DIR,params.subjectName,'mri','T1.nii.gz') ' ' ...
            fullfile(SUBJECTS_DIR,params.subjectName,'mri','brainmask.nii.gz') ' -f 0.35\n']);
        fprintf(fid,['mri_convert ' ...
            fullfile(SUBJECTS_DIR,params.subjectName,'mri','brainmask.nii.gz') ' ' ...
            fullfile(SUBJECTS_DIR,params.subjectName,'mri','brainmask.mgz') '\n']);
        fprintf(fid,'recon-all -s $SUBJ -autorecon2 -autorecon3\n');
    else
        fprintf(fid,'recon-all -i $SESS/MPRAGE/001/ACPC/MPRAGE.ACPC.nii.gz -s $SUBJ -all\n');
    end
else
    matlab_string = [matlab_string ...
        'sort_nifti(''$SESS'',''$dicomDir'',$useMRIcron,$isGE);'];
end
matlab_string = [matlab_string ...
    'skull_strip(''$SESS'',''$SUBJ'');' ...
    'segment_anat(''$SESS'',''$SUBJ'');' ...
    'xhemi_check(''$SESS'',''$SUBJ'');'];
if params.topup
    matlab_string = [matlab_string 'topup(''$SESS'');'];
end
%% Add motion correction scripts
matlab_string = ([matlab_string ...
    'params.sessionDir=''' params.sessionDir ''';' ...
    'params.despike=' num2str(params.despike) ';' ...
    'params.slicetiming=' num2str(params.slicetiming) ';' ...
    'params.refvol=' num2str(params.refvol) ';' ...
    'params.regFirst=' num2str(params.regFirst) ';' ...
    'params.topup=' num2str(params.topup) ';']);
for rr = 1:params.numRuns
    matlab_string = ([matlab_string ...
        'motion_slice_correction(params,' num2str(rr) ');']);
end
%% Add functional scripts
for rr = 1:params.numRuns
    func = 'rf';
    matlab_string = [matlab_string ...
        'register_func(''$SESS'',''$SUBJ'',' num2str(rr) ',1,''' func ''');' ...
        'project_anat2func(''$SESS'',' num2str(rr) ',''' func ''');' ...
        'create_regressors(''$SESS'',' num2str(rr) ',''' func ''',''detrend'',' ...
        num2str(params.lowHz) ',' num2str(params.highHz) ',' num2str(params.physio) ',' ...
        num2str(params.motion) ',' num2str(params.anat) ');' ...
        'remove_noise(''$SESS'',' num2str(rr) ',''' func ''',' ...
        num2str(params.task) ',' num2str(params.anat) ',' num2str(params.motion) ',' ...
        num2str(params.physio) ');'];
    if params.localWM
        matlab_string = [matlab_string ...
            'remove_localWM(''$SESS'',' num2str(rr) ',''d' func ''');' ...
            'temporal_filter(''$SESS'',' num2str(rr) ',''wd' func ''',''' params.filtType ''',' ...
            num2str(params.lowHz) ',' num2str(params.highHz) ');' ...
            'smooth_vol_surf(''$SESS'',' num2str(rr) ',5,''wd' func '.tf'');'];
    else
        matlab_string = [matlab_string ...
            'temporal_filter(''$SESS'',' num2str(rr) ',''d' func ''',''' params.filtType ''',' ...
            num2str(params.lowHz) ',' num2str(params.highHz) ');' ...
            'smooth_vol_surf(''$SESS'',' num2str(rr) ',5,''d' func '.tf'');'];
    end
end
fprintf(fid,['matlab -nodisplay -nosplash -r ' matlab_string '"']);
fclose(fid);