function create_all_script(session_dir,subject_name,outDir,job_name,reconall,slicetiming,refvol,numRuns,filtType,lowHz,highHz,physio,motion,task,localWM,anat)

% Writes shell scripts to preprocess anatomical and functional MRI data
%
%   Usage:
%   create_all_script(session_dir,subject_name,outDir,job_name,reconall,slicetiming,refvol,numRuns,filtType,lowHz,highHz,physio,motion,task,localWM,anat)
%
%   Written by Andrew S Bock Nov 2015

%% Set initial parameters
fname = fullfile(outDir,[job_name '_all.sh']);
fid = fopen(fname,'w');
fprintf(fid,'#!/bin/bash\n');
fprintf(fid,['SESS=' session_dir '\n']);
fprintf(fid,['SUBJ=' subject_name '\n\n']);
%% Add anatomical scripts
if reconall % If a new subject, for which recon-all has not been run
    fprintf(fid,'matlab -nodisplay -nosplash -r "sort_nifti(''$SESS'');"\n');
    fprintf(fid,'recon-all -i $SESS/MPRAGE/001/ACPC/MPRAGE.ACPC.nii.gz -s $SUBJ -all\n');
    matlab_string = ([...
        '"skull_strip(''$SESS'',''$SUBJ'');' ...
        'segment_anat(''$SESS'',''$SUBJ'');xhemi_check(''$SESS'',''$SUBJ'');' ...
        'motion_slice_correction(''$SESS'',1,' num2str(slicetiming) ',' num2str(refvol) ');"']);
    fprintf(fid,['matlab -nodisplay -nosplash -r ' matlab_string]);
else
    matlab_string = ([...
        '"sort_nifti(''$SESS'');skull_strip(''$SESS'',''$SUBJ'');' ...
        'segment_anat(''$SESS'',''$SUBJ'');xhemi_check(''$SESS'',''$SUBJ'');' ...
        'motion_slice_correction(''$SESS'',1,' num2str(slicetiming) ',' num2str(refvol) ');']);
end
%% Add functional scripts
for rr = 1:numRuns
    func = 'rf';
    if ~localWM
        matlab_string = ([matlab_string ...
            'register_func(''$SESS'',''$SUBJ'',' num2str(rr) ',1,''' func ''');' ...
            'project_anat2func(''$SESS'',' num2str(rr) ',''' func ''');' ...
            'create_regressors(''$SESS'',' num2str(rr) ',''' func ''',''detrend'',' ...
            num2str(lowHz) ',' num2str(highHz) ',' num2str(physio) ',' ...
            num2str(motion) ',' num2str(anat) ');' ...
            'remove_noise(''$SESS'',' num2str(rr) ',''' func ''',' ...
            num2str(task) ',' num2str(anat) ',' num2str(motion) ',' ...
            num2str(physio) ');' ...
            'temporal_filter(''$SESS'',' num2str(rr) ',''d' func ''',''' filtType ''',' ...
            num2str(lowHz) ',' num2str(highHz) ');' ...
            'smooth_vol_surf(''$SESS'',' num2str(rr) ',5,''d' func '.tf'')"']);
    else
        matlab_string = ([matlab_string ...
            'register_func(''$SESS'',''$SUBJ'',' num2str(rr) ',1,''' func ''');' ...
            'project_anat2func(''$SESS'',' num2str(rr) ',''' func ''');' ...
            'create_regressors(''$SESS'',' num2str(rr) ',''' func ''',''detrend'',' ...
            num2str(lowHz) ',' num2str(highHz) ',' num2str(physio) ',' ...
            num2str(motion) ',' num2str(anat) ');' ...
            'remove_noise(''$SESS'',' num2str(rr) ',''' func ''',' ...
            num2str(task) ',' num2str(anat) ',' num2str(motion) ',' ...
            num2str(physio) ');' ...
            'remove_localWM(''$SESS'',' num2str(rr) ',''d' func ''');' ...
            'temporal_filter(''$SESS'',' num2str(rr) ',''wd' func ''',''' filtType ''',' ...
            num2str(lowHz) ',' num2str(highHz) ');' ...
            'smooth_vol_surf(''$SESS'',' num2str(rr) ',5,''wd' func '.tf'');']);
    end
end
fprintf(fid,['matlab -nodisplay -nosplash -r ' matlab_string '"\n']);
fclose(fid);